// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADQr86MJKaT1blIGSIztYDsLqA_rfYpwQ',
    appId: '1:251059549513:web:d2f7a7b3c6736685a51698',
    messagingSenderId: '251059549513',
    projectId: 'monarch-ag',
    authDomain: 'monarch-ag.firebaseapp.com',
    storageBucket: 'monarch-ag.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyACYGxF_02zwXnev5BGDOboBaAMiz1OY',
    appId: '1:251059549513:android:3d7203f5bdd9dafda51698',
    messagingSenderId: '251059549513',
    projectId: 'monarch-ag',
    storageBucket: 'monarch-ag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQisKdD87FXoducsEe50UJW--DI8c57-I',
    appId: '1:251059549513:ios:5643161a3bcc876fa51698',
    messagingSenderId: '251059549513',
    projectId: 'monarch-ag',
    storageBucket: 'monarch-ag.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
